// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTrace_legacy returns the embedded CollectionSpec for trace_legacy.
func loadTrace_legacy() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Trace_legacyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load trace_legacy: %w", err)
	}

	return spec, err
}

// loadTrace_legacyObjects loads trace_legacy and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*trace_legacyObjects
//	*trace_legacyPrograms
//	*trace_legacyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTrace_legacyObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTrace_legacy()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// trace_legacySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trace_legacySpecs struct {
	trace_legacyProgramSpecs
	trace_legacyMapSpecs
	trace_legacyVariableSpecs
}

// trace_legacyProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trace_legacyProgramSpecs struct {
	TracepointSysEnterAccept4 *ebpf.ProgramSpec `ebpf:"tracepoint__sys_enter_accept4"`
	TracepointSysEnterConnect *ebpf.ProgramSpec `ebpf:"tracepoint__sys_enter_connect"`
	TracepointSysEnterExecve  *ebpf.ProgramSpec `ebpf:"tracepoint__sys_enter_execve"`
	TracepointSysExitAccept4  *ebpf.ProgramSpec `ebpf:"tracepoint__sys_exit_accept4"`
	TracepointSysExitExecve   *ebpf.ProgramSpec `ebpf:"tracepoint__sys_exit_execve"`
}

// trace_legacyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trace_legacyMapSpecs struct {
	Accept4Sockaddr *ebpf.MapSpec `ebpf:"accept4_sockaddr"`
	Pb              *ebpf.MapSpec `ebpf:"pb"`
}

// trace_legacyVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trace_legacyVariableSpecs struct {
}

// trace_legacyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTrace_legacyObjects or ebpf.CollectionSpec.LoadAndAssign.
type trace_legacyObjects struct {
	trace_legacyPrograms
	trace_legacyMaps
	trace_legacyVariables
}

func (o *trace_legacyObjects) Close() error {
	return _Trace_legacyClose(
		&o.trace_legacyPrograms,
		&o.trace_legacyMaps,
	)
}

// trace_legacyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTrace_legacyObjects or ebpf.CollectionSpec.LoadAndAssign.
type trace_legacyMaps struct {
	Accept4Sockaddr *ebpf.Map `ebpf:"accept4_sockaddr"`
	Pb              *ebpf.Map `ebpf:"pb"`
}

func (m *trace_legacyMaps) Close() error {
	return _Trace_legacyClose(
		m.Accept4Sockaddr,
		m.Pb,
	)
}

// trace_legacyVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTrace_legacyObjects or ebpf.CollectionSpec.LoadAndAssign.
type trace_legacyVariables struct {
}

// trace_legacyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTrace_legacyObjects or ebpf.CollectionSpec.LoadAndAssign.
type trace_legacyPrograms struct {
	TracepointSysEnterAccept4 *ebpf.Program `ebpf:"tracepoint__sys_enter_accept4"`
	TracepointSysEnterConnect *ebpf.Program `ebpf:"tracepoint__sys_enter_connect"`
	TracepointSysEnterExecve  *ebpf.Program `ebpf:"tracepoint__sys_enter_execve"`
	TracepointSysExitAccept4  *ebpf.Program `ebpf:"tracepoint__sys_exit_accept4"`
	TracepointSysExitExecve   *ebpf.Program `ebpf:"tracepoint__sys_exit_execve"`
}

func (p *trace_legacyPrograms) Close() error {
	return _Trace_legacyClose(
		p.TracepointSysEnterAccept4,
		p.TracepointSysEnterConnect,
		p.TracepointSysEnterExecve,
		p.TracepointSysExitAccept4,
		p.TracepointSysExitExecve,
	)
}

func _Trace_legacyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed trace_legacy_bpfel.o
var _Trace_legacyBytes []byte
