// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type traceConfig struct {
	_           structs.HostLayout
	TxThreshold uint64
	RxThreshold uint64
}

type traceConnInfo struct {
	_        structs.HostLayout
	RxBytes  uint64
	TxBytes  uint64
	WarnedRx uint32
	WarnedTx uint32
	Daddr    uint32
	Dport    uint16
	Family   uint16
	Comm     [16]int8
}

type traceConnKey struct {
	_   structs.HostLayout
	Pid uint32
	Fd  uint32
}

// loadTrace returns the embedded CollectionSpec for trace.
func loadTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load trace: %w", err)
	}

	return spec, err
}

// loadTraceObjects loads trace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*traceObjects
//	*tracePrograms
//	*traceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// traceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceSpecs struct {
	traceProgramSpecs
	traceMapSpecs
	traceVariableSpecs
}

// traceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceProgramSpecs struct {
	TracepointSysEnterAccept4  *ebpf.ProgramSpec `ebpf:"tracepoint__sys_enter_accept4"`
	TracepointSysEnterClose    *ebpf.ProgramSpec `ebpf:"tracepoint__sys_enter_close"`
	TracepointSysEnterConnect  *ebpf.ProgramSpec `ebpf:"tracepoint__sys_enter_connect"`
	TracepointSysEnterExecve   *ebpf.ProgramSpec `ebpf:"tracepoint__sys_enter_execve"`
	TracepointSysEnterRead     *ebpf.ProgramSpec `ebpf:"tracepoint__sys_enter_read"`
	TracepointSysEnterRecvfrom *ebpf.ProgramSpec `ebpf:"tracepoint__sys_enter_recvfrom"`
	TracepointSysEnterSendto   *ebpf.ProgramSpec `ebpf:"tracepoint__sys_enter_sendto"`
	TracepointSysEnterWrite    *ebpf.ProgramSpec `ebpf:"tracepoint__sys_enter_write"`
	TracepointSysExitAccept4   *ebpf.ProgramSpec `ebpf:"tracepoint__sys_exit_accept4"`
	TracepointSysExitExecve    *ebpf.ProgramSpec `ebpf:"tracepoint__sys_exit_execve"`
	TracepointSysExitRead      *ebpf.ProgramSpec `ebpf:"tracepoint__sys_exit_read"`
	TracepointSysExitRecvfrom  *ebpf.ProgramSpec `ebpf:"tracepoint__sys_exit_recvfrom"`
	TracepointSysExitSendto    *ebpf.ProgramSpec `ebpf:"tracepoint__sys_exit_sendto"`
	TracepointSysExitWrite     *ebpf.ProgramSpec `ebpf:"tracepoint__sys_exit_write"`
}

// traceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceMapSpecs struct {
	Accept4Sockaddr *ebpf.MapSpec `ebpf:"accept4_sockaddr"`
	ConfigMap       *ebpf.MapSpec `ebpf:"config_map"`
	ConnStatsMap    *ebpf.MapSpec `ebpf:"conn_stats_map"`
	IoEnterArgs     *ebpf.MapSpec `ebpf:"io_enter_args"`
	Rb              *ebpf.MapSpec `ebpf:"rb"`
}

// traceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceVariableSpecs struct {
}

// traceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceObjects struct {
	tracePrograms
	traceMaps
	traceVariables
}

func (o *traceObjects) Close() error {
	return _TraceClose(
		&o.tracePrograms,
		&o.traceMaps,
	)
}

// traceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceMaps struct {
	Accept4Sockaddr *ebpf.Map `ebpf:"accept4_sockaddr"`
	ConfigMap       *ebpf.Map `ebpf:"config_map"`
	ConnStatsMap    *ebpf.Map `ebpf:"conn_stats_map"`
	IoEnterArgs     *ebpf.Map `ebpf:"io_enter_args"`
	Rb              *ebpf.Map `ebpf:"rb"`
}

func (m *traceMaps) Close() error {
	return _TraceClose(
		m.Accept4Sockaddr,
		m.ConfigMap,
		m.ConnStatsMap,
		m.IoEnterArgs,
		m.Rb,
	)
}

// traceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceVariables struct {
}

// tracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracePrograms struct {
	TracepointSysEnterAccept4  *ebpf.Program `ebpf:"tracepoint__sys_enter_accept4"`
	TracepointSysEnterClose    *ebpf.Program `ebpf:"tracepoint__sys_enter_close"`
	TracepointSysEnterConnect  *ebpf.Program `ebpf:"tracepoint__sys_enter_connect"`
	TracepointSysEnterExecve   *ebpf.Program `ebpf:"tracepoint__sys_enter_execve"`
	TracepointSysEnterRead     *ebpf.Program `ebpf:"tracepoint__sys_enter_read"`
	TracepointSysEnterRecvfrom *ebpf.Program `ebpf:"tracepoint__sys_enter_recvfrom"`
	TracepointSysEnterSendto   *ebpf.Program `ebpf:"tracepoint__sys_enter_sendto"`
	TracepointSysEnterWrite    *ebpf.Program `ebpf:"tracepoint__sys_enter_write"`
	TracepointSysExitAccept4   *ebpf.Program `ebpf:"tracepoint__sys_exit_accept4"`
	TracepointSysExitExecve    *ebpf.Program `ebpf:"tracepoint__sys_exit_execve"`
	TracepointSysExitRead      *ebpf.Program `ebpf:"tracepoint__sys_exit_read"`
	TracepointSysExitRecvfrom  *ebpf.Program `ebpf:"tracepoint__sys_exit_recvfrom"`
	TracepointSysExitSendto    *ebpf.Program `ebpf:"tracepoint__sys_exit_sendto"`
	TracepointSysExitWrite     *ebpf.Program `ebpf:"tracepoint__sys_exit_write"`
}

func (p *tracePrograms) Close() error {
	return _TraceClose(
		p.TracepointSysEnterAccept4,
		p.TracepointSysEnterClose,
		p.TracepointSysEnterConnect,
		p.TracepointSysEnterExecve,
		p.TracepointSysEnterRead,
		p.TracepointSysEnterRecvfrom,
		p.TracepointSysEnterSendto,
		p.TracepointSysEnterWrite,
		p.TracepointSysExitAccept4,
		p.TracepointSysExitExecve,
		p.TracepointSysExitRead,
		p.TracepointSysExitRecvfrom,
		p.TracepointSysExitSendto,
		p.TracepointSysExitWrite,
	)
}

func _TraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed trace_bpfel.o
var _TraceBytes []byte
